import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import {SiHashnode} from 'react-icons/si'
import Image from 'next/image';
import avatar from '../public/avatar.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import {useState} from 'react';

export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark': ''}>
      <Head>
        <title>Brian Bud Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-60 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Brian Bud</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#" target='_blank'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='font-extrabold text-transparent text-5xl bg-clip-text bg-gradient-to-r from-cyan-500 to-cyan-700'>Brian Buddhadasa</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Software Developer</h3>
            <p className='text-xl py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>Hello, I am a web developer based in Toronto, Canada. Two things I enjoy are always learning and creating, thus 
            I'm open to learning more from others and to be part of a team that create cool solutions to interesting problems.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 pt-0 text-gray-600 dark:text-gray-50'>
            <a href='https://www.linkedin.com/in/brianbud/' target='_blank'><AiFillLinkedin/></a>
            <a href='https://github.com/brianbud' target='_blank'><AiFillGithub/></a>
            <a href='https://brianbud.hashnode.dev/' target='_blank'><SiHashnode/></a>
            <a href='https://twitter.com/brianbud_' target='_blank'><AiFillTwitterCircle/></a>
          </div>
          <div className='relative mx-auto w-80 h-80 mt-10 md:h-96 md:w-96'>
            <Image className='rounded-full' layout='fill' objectFit='cover' src={avatar} />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl pt-10 dark:text-white'>About me</h3>
            <p className='text-md pb-5 leading-8 text-gray-800 dark:text-white'>I'm a lifelong learner and creator.</p>
            <p className='text-md leading-8 text-gray-800 dark:text-white'>I have a Bachelor's degree in Business Administration, a diploma in Marketing and my interest is in Software Development.
            At a young age, I enjoyed creating whether it's through arts, music or videos. I also was always interested in Tech, from reading Techcrunch daily to watching Tech Youtubers.
            Coding scratches that itch of being able to create something cool with just a laptop and internet; I enjoy being resourceful.</p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-large font-medium pt-8 pb-2'>Designs</h3>
              <p className='py-2'>iste incidunt aspernatur esse sequi facere corporis pariatur deserunt velit eius dolor fuga tempora quas ipsum ab.</p>
              <h4 className='py-4 text-teal-600'>Tools I use</h4>
              <p className='text-gray-800 py-1'>HTML</p>
              <p className='text-gray-800 py-1'>CSS</p>
              <p className='text-gray-800 py-1'>Tailwind</p>
              <p className='text-gray-800 py-1'>JavaScript</p>
              <p className='text-gray-800 py-1'>React</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-large font-medium pt-8 pb-2'>Complimentary skills</h3>
              <p className='py-2'>iste incidunt aspernatur esse sequi facere corporis pariatur deserunt velit eius dolor fuga tempora quas ipsum ab.</p>
              <h4 className='py-4 text-teal-600'>Tools I use</h4>
              <p className='text-gray-800 py-1'>2 years in Sales</p>
              <p className='text-gray-800 py-1'>Customer Service</p>
              <p className='text-gray-800 py-1'>Leadership roles</p>
              <p className='text-gray-800 py-1'>Googling</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100}/>
              <h3 className='text-large font-medium pt-8 pb-2'>Designs</h3>
              <p className='py-2'>iste incidunt aspernatur esse sequi facere corporis pariatur deserunt velit eius dolor fuga tempora quas ipsum ab.</p>
              <h4 className='py-4 text-teal-600'>Tools I use</h4>
              <p className='text-gray-800 py-1'>HTML</p>
              <p className='text-gray-800 py-1'>CSS</p>
              <p className='text-gray-800 py-1'>JavaScript</p>
              <p className='text-gray-800 py-1'>Tailwind</p>
              <p className='text-gray-800 py-1'>React</p>
            </div>
          </div>
        </section>
        <section className="py-0">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Projects</h3>
            <p className="text-md leading-8 text-gray-800 dark:text-white">
              Some projects I'm proud to showcase
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
              <h3 className='text-center text-2xl dark:text-white'>Project name</h3>
              <p className='dark:text-white'>This project is made to help with this problem and is made with these languages</p>
              <ul className='flex items-center justify-center py-5'>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-0' href="#">Demo</a></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-5' href="#">Code</a></li>
            </ul>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
               <h3 className='text-center text-2xl dark:text-white'>Project name</h3>
              <p className='dark:text-white'>This project is made to help with this problem and is made with these languages</p>
              <ul className='flex items-center justify-center py-5'>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-0' href="#">Demo</a></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-5' href="#">Code</a></li>
            </ul>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
               <h3 className='text-center text-2xl dark:text-white'>Project name</h3>
              <p className='dark:text-white'>This project is made to help with this problem and is made with these languages</p>
              <ul className='flex items-center justify-center py-5'>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-0' href="#">Demo</a></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-5' href="#">Code</a></li>
            </ul>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
               <h3 className='text-center text-2xl dark:text-white'>Project name</h3>
              <p className='dark:text-white'>This project is made to help with this problem and is made with these languages</p>
              <ul className='flex items-center justify-center pt-5'>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-0' href="#">Demo</a></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-5' href="#">Code</a></li>
            </ul>
            </div>
          </div>
        </section>
        <div className='text-center pb-10 '>
            <h3 className='text-2xl md:text-3xl dark:text-white'>Get In Touch</h3>
            <h2 className='font-extrabold text-transparent text-4xl bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-600'><a href='mailto:hello@brianbud.com'>hello@brianbud.com</a></h2>
          </div>
       </main>
       <footer class="text-center bg-gradient-to-r from-cyan-900 to-teal-900">
            <div class="pt-5 flex justify-center gap-4 ">
                <a class="link link-hover" target='_blank' href='https://www.linkedin.com/in/brianbud/'>LinkedIn</a> 
                <a class="link link-hover" target='_blank' href='https://github.com/brianbud'>Github</a> 
                <a class="link link-hover" target='_blank' href='https://brianbud.hashnode.dev/'>Blog</a> 
                <a class="link link-hover" target='_blank' href='https://twitter.com/brianbud_'>Twitter</a>
            </div> 
            <div class='pb-5'>
              <p>Portfolio made with NextJS and Tailwind</p>
            </div>
          </footer>
    </div>
  );
}
